### PR TITLE
Return a desired IP if specified in instance tags.

### PR DESCRIPTION
**Pull request by tomwans**
If the tag key 'Address' is specified on an instance, use that as the IP for DNS.

### CODE REVIEW

**Comment by mattmoyer** [comment]
+1

**Comment by mwhooker** [comment]
+1

but check out these different flavors

``` python
def determine_address(instance):
    try:
        ip = instance.tags['Address']
    except KeyError:
        ip = (instance.ip_address or instance.private_ip_address)
    return ip.encode("ascii")
```

``` python
def determine_address(instance):
    ip = instance.tags.get('Address',
        (instance.ip_address or instance.private_ip_address))
    return ip.encode("ascii")
```

personally I prefer the first

**Comment by mwhooker** [comment]
``` python
return instance.tags.get('Address') or instance.ip_address or instance.private_ip_address 
```

**Comment by tomwans** [comment]
@mwhooker, implemented your python-fu.

**Comment by whilp** [comment]
Right on!

**Pull request merged**
